### ISSUE TITLE
Implement SSL support

### ISSUE THREAD

**Issue by jocel1** [pdezwart/php-amqp#118]
Hi,

Either https://github.com/BraveSirRobin/amqphp or https://github.com/videlalvaro/php-amqplib implements a way to connect to RabbitMQ through SSL.

Do you plan to add this kind of feature ?

Thanks !
  Jocelyn

**Comment by lstrojny** [comment]
Any takers welcome, as I personally lack the time and especially the knowledge on how to properly implement SSL support using OpenSSL and I rather not support it and have a broken implementation than support it badly.

**Comment by pinepain** [comment]
rabbitmq-c has already SSL support, so for us it should not be a problem. I propose to pass key and cert path inside with other config parameters in `$credentials` argument to `AMQPConnection::__construct()` and also add getters and setters for key and cert (`{get,set}SecureKey`, `{get,set}SecureCert`?). There should be method to check whether established connection is secure one (`isSecure`?). Setting key or cert when connection already established should fail.

**Comment by lstrojny** [comment]
@pinepain do you know anything about the implementation with regards to how they handle certificates?

**Comment by pinepain** [comment]
rabbitmq-c uses OpenSSL (by default, there are other SSL implementations support too). I'm not into crypto, incluting TLS/SSL internals, but from rabbitmq-c activity (I keep eye on it) and it examples, it is not necessary to dive into internals, while you just have to create SSL socket (in terms of rabbitmq-c library) and then use it instead of tcp one.

I can try to play with it when I will have some free time (beta ETA from 2 days to about 2 weeks).

**Comment by pinepain** [comment]
rabbitmq-c uses OpenSSL (by default, there are other SSL implementations support too). I'm not into crypto, incluting TLS/SSL internals, but from rabbitmq-c activity (I keep eye on it) and it examples, it is not necessary to dive into internals, while you just have to create SSL socket (in terms of rabbitmq-c library) and then use it instead of tcp one.

If interface I proposed fits php-amqp extension needs, I can try to play with SSL implementation when I will have some free time (beta ETA from 2 days to about 2 weeks).

**Comment by digipigeon** [comment]
+1 for this feature.

**Comment by d3xt3r01** [comment]
+1, the only reason I'm not using this yet.

**Comment by EagleEyeJohn** [comment]
@d3xt3r01 Couldn't you overcome the lack of SSL support by using a SSH tunnel?

**Comment by d3xt3r01** [comment]
I'm not in full control over all consumers.

**Comment by pinepain** [comment]
SSL connection support added in PR https://github.com/pdezwart/php-amqp/pull/205. 

Please, give it a look and test a bit. I would really appreciate any feedback you can provide.

**Comment by pinepain** [comment]
ping @lstrojny in case #205 fits our needs this can be closed, I guess.

**Comment by prolic** [comment]
Can be closed?

**Comment by lstrojny** [comment]
Indeed.
