### ISSUE TITLE
Publisher Acknowledgements

### ISSUE THREAD

**Issue by rcrowe** [pdezwart/php-amqp#136]
I've looked through the documentation / code / existing issues & couldn't find an answer on *confirms*. So apologies if this is a duplicate.

The closest I've found was on #24 but the last message just states `Very old issue. Closing.`

Is there a way to do confirms?

**Comment by pinepain** [comment]
There are not support for [confirms](https://www.rabbitmq.com/confirms.html) yet. But it may be added.

**Comment by c-datculescu** [comment]
Hello. We have recently ran into some weird issues in which cutting off the network between the broker and the publisher ends up in publisher still pushing messages for some amount of time. 

isConnected method returns true although network is down, which can lead to some lost messages. Publisher confirms would help mitigate this issue.

Is it possible to have this implemented?

**Comment by pinepain** [comment]
Hi, sorry for late reply. Yeah, havin `isConnected` return `true` while low-level underlying socket is closed is a known problem - you can't exactly say whether socket without using it.

At this moment there are no [Confirms (aka Publisher Acknowledgements)](https://www.rabbitmq.com/confirms.html) confirms support, mostly because this extension implements AMQP protocol in synchronous way (mostly).

You can try [php-amqplib](https://github.com/videlalvaro/php-amqplib) PHP library by @videlalvaro.

Personally I realize that publisher confirm is important feature and we should add it support. There was discussion about re-designing this extension API, so I guess missed features will be added under that redesigning and refactoring, but no ETA for now. The main problem to add support for most features is that extension is written in synchronous manner (under the hood extension uses [rabbitmq-c](https://github.com/alanxz/rabbitmq-c) C library which written in synchronous manner), so redesigning will lead to re-writing that library or writing new one, both ways are not trivial.

**Comment by c-datculescu** [comment]
Hi. No need to appologise, the work done on maintaining this extension is awesome and it covers most of the usual cases quite ok while being easy to use. Wish i could contribute more in the developmen, but this is unknow territory for me.

The main issue with using phpamqplib is the difference in the api (at least last time i checked). Would be awesome if the apis would be similar. Beyond that, there is a fair amount of testing to be done if the dependencies change.

From what i see rabbitmq-c is actively maintained and releases are coming in quite ok, so i hope in the future it will get better.

Thank you very much for the clarification.

**Comment by c-datculescu** [comment]
Hello.

In the end we went with implementing a bridge between the two libraries, mostly we will use the amqp extension for listening and the php-amqplib for publishing (because of support for publisher acknowledgements). Is available under my profile :)

Best,
Cristian.

**Comment by prolic** [comment]
@pinepain I really would like to see this feature in the php extension!

**Comment by olekhy** [comment]
:+1:  this feature is mandatory for me.

**Comment by EagleEyeJohn** [comment]
@c-datculescu we went with amqp extension for publishing as it's performance is 10-12x that of php-amqplib when we tested them with 50+ publishing processes at a combined rate of ~1200 messages per second.  php-amqplib is simply too slow to achieve the speed we need.  However, php-amqplib is (in our experience) 100% reliable whereas php-amqp is not, and so we log failed publishes and have a backup process which will use php-amqplib to publish messages that  php-amqp could not.

**Comment by c-datculescu** [comment]
That is weird. Under a workload of around 10 million messages a day we didnt happen to lose messages because of publishing.

In extreme cases the publisher can return true though even if the message didnt reach the server, but we only experienced that under certain resource starvation at some level (source machine, target machine, load balancer, etc.) so we didnt really consider those messages exactly "lost". Under normal operating conditions we didnt lose a single message afaik.

**Comment by pinepain** [comment]
@EagleEyeJohn Can you provide minimal code and specify configuration under which you experienced messages loss? Maybe you fill new issue with details about that losses?

**Comment by pinepain** [comment]
Hi, I tried to add with PR https://github.com/pdezwart/php-amqp/pull/203 [Confirms (aka Publisher Acknowledgements)](https://www.rabbitmq.com/confirms.html) support.

Please, give it a look and test a bit. I would really appreciate any feedback you can provide.

**Comment by c-datculescu** [comment]
Hello.

I have tested a little bit today, and all seems to be working as expected. Will carry on with a little more tests in the following days.

Thanks for the great effort put into this.

**Comment by c-datculescu** [comment]
Hi. I did a little more testing, and i am getting some weird exceptions (Unexpected server method). Didn't got to dig too much into the exception, all that i know right now is that it seems to be triggered when there is a large number of publishing operations per second (it generally breaks down at some point after running at around 16k messages/second).

I hope i will get more time to spend on this soon.

**Comment by prolic** [comment]
Issue can get closed?

**Comment by lstrojny** [comment]
Indeed
