### ISSUE TITLE
AMQPQueue passed to `consume` callable when consuming multiple queues

### ISSUE THREAD

**Issue by tompedals** [pdezwart/php-amqp#165]
When consuming multiple queues (as in the `amqpqueue_consume_multiple.phpt` test) the AMQPQueue instance that is passed to the callback will always be the queue which was passed the callable. If the message sent to the other queue I would expect that AMQPQueue instance to be passed to the callback.

At the moment I'm using a direct exchange so using the message routing key to determine which queue the message was for, but it would be nice if it works as I expected.

Is this an issue or a misunderstanding on my part of how the feature works?

**Comment by pinepain** [comment]
Hi! Yes, this is expected behavior, though it is not intuitive. This is happens due to internal legacy architecture. Eliminating this issue under current architecture will significantly increase code complexity and possible point of failures. We expect this to be fixed in next major release (no ETA for now).

**Comment by tompedals** [comment]
Thanks for the clarification @pinepain. I've worked around it for now as I can figure out which queue I need from the message routing key.
