### ISSUE TITLE
Update PHP7 compatibility status

### ISSUE THREAD

**Issue by sshilko** [pdezwart/php-amqp#167]
Please update wiki about whether its php7-ready
https://github.com/gophp7/gophp7-ext/wiki/extensions-catalog

**Comment by jippi** [comment]
:+1:

**Comment by jderusse** [comment]
:+1: PHP7 beta 1 is released

**Comment by guilhermeblanco** [comment]
**Tests** YES
**Docs** NO
**Works on PHP5** YES
**Works on PHP7** NO
**Good on PHP 7** NO

Does not compile, does not work as it currently stands on PHP7. I started to do changes to turn it into compatible through this compare: https://github.com/pdezwart/php-amqp/compare/master...guilhermeblanco:phpng
It's still heavily WIP and not compiling... yet. =(

**Comment by pinepain** [comment]
@guilhermeblanco Nice job! Can you clarify whether PHP-7 changes will be BC for PHP-5?

**Comment by lstrojny** [comment]
@guilhermeblanco awesome!

**Comment by guilhermeblanco** [comment]
@pinepain They cannot be... too many "catastrophic" changes to try BC (specially around string and hash APIs).
I also took advantage of this update to remove deprecated features on the extension.

**Comment by pinepain** [comment]
@guilhermeblanco I've looked through changes you've made. Impressive. How do you see extension roadmap?

P.S.: we have Vagrant file and provisioner script in repo, please update them according to your dev environment so others can join you.

**Comment by guilhermeblanco** [comment]
@pinepain there're so many changes required that I don't know how to start sometimes.
Usually I take the https://wiki.php.net/phpng-upgrading page and choose one of the issues, then I start updating everywhere. However, this extension seems to lack a lot of update in the last couple of years that scares me sometimes.
A good example is this method: https://github.com/pdezwart/php-amqp/blob/master/amqp_connection.c#L901
It's been quite a while (IIRC, since PHP 5.3) that it's not required to call `zend_object_store_get_object` (in PHP7 this is now `Z_OBJ_P`) because ZPP already does the cast to you. This method could be updated into a PHP 5.3+ compatible way like this:

```cpp
PHP_METHOD(amqp_connection_class, getPassword)
{
	amqp_connection_object *connection;

	if (zend_parse_method_parameters(ZEND_NUM_ARGS() TSRMLS_CC, getThis(), "O", &connection, amqp_connection_class_entry) == FAILURE) {
		return;
	}

	/* Copy the password to the amqp object */
	RETURN_STRING(connection->password);
}
```

Also, it looks like PHP is slowly abstracting data types into objects (such as new `zend_string`) and I feel we should use it when needed (such as for `password` property in previous example) which would drastically simplify the API too. 
Extension is quite usable and somewhat reliable, but many other times I see memory being leaked in its code (ie https://github.com/pdezwart/php-amqp/blob/master/amqp_exchange.c#L579 this methods never free's `ini_arr` after its copy at line 620) that I wonder if it isn't time for a good rewrite. As of now, I'm just trying to move on getting it compiled and working with my current codebase.

My roadmap is to get it working asap with the code as it currently stands. I am only free max 1h every day to update the code, so it might take a while for me to finish. I did nothing different than provision Rasmus' php7dev box, checkout php-amqp and try to compile. I removed old PHP version support as code need to change because of API changes, do it makes no point to have it there anymore. I also removed code marked as `deprecated` on userland API.
If everybody really wants to do onboard, we could rethink the end-user API and release as 2.0, but that's not up to me. In the meantime, I'll try to get it working on my limited time.

**Comment by pinepain** [comment]
@guilhermeblanco I really appreciate what you already done. I guess working now is better than perfect but never. I will try to jump on board, but for now I don't have even free 1h like you, even per week. Though, I'm really interested in PHP7 changes and will try to do my best to provide any help, fells free to contact me here or personally, if I can do anything, I spent a while on this extension and a bit on rabbitmq-c which is used under the hood.

There are a lot of really outdated code like you provided (`zend_object_store_get_object` and so on). There was huge upgrading few releases before, but it was focused more on adding proper persistence and rabbitmq-c interaction. I've tried to clean a bit all this mess, but had to limit my efforts to do not write new extension instead of cleanup :smile:. As to objects, you can see that there are plain C structs instead of rich PHP objects in use, which leads to extra methods to get object debug info. And this is not even worst part.

That ini array duplication part was done by me and looks like we talk about `ini_arr_tmp` (raw `ini_arr` comes as argument), which allocates (conditionally) at [amqp_exchange.c#L618](https://github.com/pdezwart/php-amqp/blob/master/amqp_exchange.c#L618) and freed at [amqp_exchange.c#L766](https://github.com/pdezwart/php-amqp/blob/master/amqp_exchange.c#L766). Probably I missed there something, but valgrind didn't tell me anything. If you see any memleak or potentially dangerous place, please, provide PR into master branch asap or at let us know and someone will try to take care of it.

As to `2.0` version, we didn't even release `1.0` version yet. So I'm a bit confused now. I'm not the big fan of monstrous BC, but on the other hands I know some really big projects which rely on this extension and expect some BC. I guess we can try to maintain two versions, one for php5 and another for php7 and then let's see how it goes.

There was talks to add asynchronous API to underlying [rabbitmq-c](https://github.com/alanxz/rabbitmq-c) library - [Suggestion for redesign #138 ](https://github.com/alanxz/rabbitmq-c/issues/138) is one of them. Without it I see no significant reason to start full end-user php-amqp API rewriting, at least immediately.

**Comment by jbboehr** [comment]
It is possible (generally, at least) to get it working on both PHP5 and PHP7. See:
https://github.com/jedisct1/libsodium-php/pull/23/files#diff-0f29a49441e3d73202e3abaab7c324b0R73
https://github.com/jbboehr/php-mustache/pull/11/files#diff-7905585bdfbda727fb2f2554f4d8a913R13
https://github.com/jbboehr/php-epeg/blob/master/epeg.c#L37

**Comment by pinepain** [comment]
@jbboehr Thanks for examples! That is exactly what I was thinking off. I guess there already is some kind of php5-to-php7 set of macro. Though, some parts of php-amqp extension are really outdated and should be rewritten.

**Comment by guilhermeblanco** [comment]
@jbboehr none of mentioned extensions heavily use hashes as AMQP, which is one are heavily affected by PHP7.
Surely we can create macros for everything and make it back-compatible, but wouldn't it be better to do a much needed cleanup and set the minimum compatibility to PHP7 in a new release?

**Comment by jbboehr** [comment]
@guilhermeblanco The hash API has changed a fair bit, I don't think simple wrapper macros will be enough for that part. It might be possible to abstract them with some inline functions, but I haven't seen or developed an example of that yet.

**Comment by hanikesn** [comment]
Hi everyone,

I have time to port this extension to php7 now, as our product depends on it. I'd like to continue your work @guilhermeblanco and collaborate in the future.

My first step would be to  get it to compile and then maybe do a bit of refactoring, where I could use some pointers as I'm not that experienced with zend engine.

**Comment by hanikesn** [comment]
Here's my first WIP, I had to comment some stuff out, but the first tests of AMQP_Connection are passing.
https://github.com/hanikesn/php-amqp/tree/phpng

**Comment by hanikesn** [comment]
Please see my PR: https://github.com/pdezwart/php-amqp/pull/173

**Comment by pinepain** [comment]
Here is my PR https://github.com/pdezwart/php-amqp/pull/181 to add PHP 7 support keeping BC for PHP 5 branch.

**Comment by pinepain** [comment]
@lstrojny I updated status, this issue can be closed now.

**Comment by lstrojny** [comment]
#181 got merged

**Comment by Taluu** [comment]
Any news for a beta (or let's be crazy, a stable) release for php7 ?

**Comment by sshilko** [comment]
1.7 works stable on php 5.6 for me

**Comment by guilhermeblanco** [comment]
1.7.0alpha1 works nicely on my php7 setup.
I'd recommend librabbitmq 0.7.1 minimum, since the sockets are now handled async internally, giving a significant performance boost.

**Comment by lstrojny** [comment]
Happy to tag a beta soon. @pinepain agreed?

**Comment by pinepain** [comment]
Sure, if there are no extra objectives and claims, I would love to see beta and then stable in a week or two. 

Does someone track resources usage (memory, connections closing, cpu) closely? If so, such users may provide fine-grained feedback.

**Comment by sshilko** [comment]
i send around 200k simple messages to rabbitmq exchange via persistent
connection, nothig special.

php 5.6.15
when switching to 1.7 from 1.6.* did not notice any performance gain or
loss: also no difference to lib 0.5.2 or 0.7.1

which is totally fine for me, maybe my rates too low to see difference

**Comment by carlwgeorge** [comment]
Can this bug be re-opened until 1.7.0 stable is released?  I am working on packages for the [IUS project](https://ius.io).

**Comment by pinepain** [comment]
ping @lstrojny can we release current beta as stable? If we merge pending PRs this will postpone possible release for a next few month.

**Comment by guilhermeblanco** [comment]
@pinepain I've used 1.7.0 alpha2 for a couple of months in production with none to very minimal issues.
It's ok to make it stable.

@carlwgeorge I hope the spec file we've done helps you

**Comment by carlwgeorge** [comment]
@guilhermeblanco What spec file is that?  I don't see one in this repo.  For our current PHP 5.6 packages, we just forked from Fedora's spec file.

**Comment by guilhermeblanco** [comment]
@carlwgeorge sorry... https://github.com/iuscommunity/wishlist/issues/52

**Comment by carlwgeorge** [comment]
No worries, I didn't realize you were working with @marksteele.  That spec file is really close to what I already had worked up.  Once 1.7.0 is released as stable we'll get our packages built fairly quickly.

**Comment by sshilko** [comment]
amqp-1.7.0alpha1 works for me since Jan 2016 fine (stable)
