### ISSUE TITLE
Expose more information about PHP API

### ISSUE THREAD

**Issue by lyrixx** [pdezwart/php-amqp#168]
Hello.

I had an issue with PHPUnit: https://github.com/sebastianbergmann/phpunit/issues/1652#issuecomment-113370059
and the maintainer of PHPUnit asked me to create an issue here

I also created a gist to easily reproduce the error: https://gist.github.com/lyrixx/c943e7e046ec325308fa#file-readme-md

I hope you got all information.

Thanks

**Comment by lstrojny** [comment]
@lyrixx can you edit the PHPUnit source code and dump the generated mock object code (at the end of `PHPUnit_Framework_MockObject_Generator::generateMock()`)?

**Comment by pinepain** [comment]
Is this issue still applied to any recent php-amqp version?

**Comment by lyrixx** [comment]
You can easily test it thanks to the gist I published ;) https://gist.github.com/lyrixx/c943e7e046ec325308fa#file-readme-md

**Comment by pinepain** [comment]
@lyrixx it looks like it still ;(. I've debugged and after adding `var_dump` noted that at the time of calling `$this->setName($name);` in constructor  `$this->__phpunit_originalObject` is not set.

from `test/vendor/phpunit/phpunit-mock-objects/src/Framework/MockObject/Generator/proxied_method.tpl.dist`:

```php
return call_user_func_array(array($this->__phpunit_originalObject, "{method_name}"), $arguments);
```
so calling `$this->setName($name);` in the same class constructor is not a good idea: `__phpunit_setOriginalObject()` mock method that set  `$__phpunit_setOriginalObject` called *after* object creation (see `\PHPUnit_Framework_MockObject_Generator::getObject()` method source).

As a quick fix you may call `parent::setName($name);` instead of `$this->setName($name);` in [Exchange.php](https://gist.github.com/lyrixx/c943e7e046ec325308fa#file-exchange-php-L9).

I also checked reflection on `AMQPExchange` and from brief look see nothing wrong or missed, especially for `AMQPExchange::setName()` method.

**Comment by lyrixx** [comment]
Oh, thanks a lot for all theses information ;)

**Comment by lyrixx** [comment]
I think we can close this issue since you find a workaround ?!

**Comment by zaq178miami** [comment]
Yeah, it can be close while we figured out that the problem reside not in extension or phpunit, but in how phpunit create proxy mocks.
