### ISSUE TITLE
v1.4.0 fails to compile against rabbitmq-c 0.7.0

### ISSUE THREAD

**Issue by ablyler** [pdezwart/php-amqp#169]
Issue was reported at https://github.com/Homebrew/homebrew-php/issues/1812

**Comment by pinepain** [comment]
Does 1.6.0beta3 works?

**Comment by ablyler** [comment]
@pinepain: yes, that version does work. is it safe for us to consider "1.6.0beta3" stable?

**Comment by pinepain** [comment]
Yes.

tl;dr

Here are the the changes made since 1.4.0 - [package.xml#L43-L73](https://github.com/pdezwart/php-amqp/blob/85f6dc3f3b4c395cfadb4f72d78998f950bd864a/package.xml#L43-L73). We had numerous fixes and improvements, but personally I didn't test it in production. We run valgrind checks and had tests, so you can give some trust to 1.6.0beta3. It is released month ago, so I guess it will become stable without any changes. At least we planned that in https://github.com/pdezwart/php-amqp/issues/140.

**Comment by ablyler** [comment]
@pinepain: thanks! i've gone ahead and updated it in homebrew-php

**Comment by pinepain** [comment]
@ablyler thanks!
