### ISSUE TITLE
AMQPconnection->pconnect() throw exception if connected.

### ISSUE THREAD

**Issue by J-Siu** [pdezwart/php-amqp#184]
According to AMQPConnection.php stub, pconnect() will initiate a connection with the AMQP broker or reuse an existing one if present. But following code will throw uncaught exception.

```
<?php

$co1 = new AMQPConnection(array('host' => HOST, 'port' => PORT, 'vhost' => VHOST, 'login' => USER, 'password' => PASS));
$co1->pconnect();

$co2 = new AMQPConnection(array('host' => HOST, 'port' => PORT, 'vhost' => VHOST, 'login' => USER, 'password' => PASS));
$co2->pconnect();

?>
```
The above code give following error:
```
PHP Fatal error:  Uncaught exception 'AMQPConnectionException' with message 'There are already established persistent connection to the same resource.' in /home/john/rmq/php/Amqp/JS-amqp-pconnect.php:7
Stack trace:
#0 /home/john/rmq/php/Amqp/JS-amqp-pconnect.php(7): AMQPConnection->pconnect()
#1 {main}
  thrown in /home/john/rmq/php/Amqp/JS-amqp-pconnect.php on line 7
```

**Comment by pinepain** [comment]
Hi, this is expected behavior. You can have only one persistent connect with the same connect (look into [Persistent connection](https://github.com/pdezwart/php-amqp#persistent-connection) readme section for more), implementation details can be found on [amqp_connection.c#L155](https://github.com/pdezwart/php-amqp/blob/24178f3f4f037a6655c99904c159a51a01c0ce8c/amqp_connection.c#L155). 

As a workaround you can introduce connection-specific credential value, say, `channel_max` or one of timeouts. For example:

```php
<?php
$default_max_channels = 256; // starting from 1.7.0 PHP_AMQP_MAX_CHANNELS = 65535

$co1 = new AMQPConnection(array(
    'host' => HOST,
    'port' => PORT,
    'vhost' => VHOST,
    'login' => USER,
    'password' => PASS,
    'channel_max' => $default_max_channels - 1
));
$co1->pconnect();

$co2 = new AMQPConnection(array(
    'host' => HOST,
    'port' => PORT,
    'vhost' => VHOST,
    'login' => USER,
    'password' => PASS,
    'channel_max' => $default_max_channels - 2
));
$co2->pconnect();
```

should give you two persistent connections (tested with php-amqp 1.6.0).

**Comment by J-Siu** [comment]
don't intend to open 2 separate connection, I actually thought co2 will get the connection already opened by co1.

**Comment by pinepain** [comment]
We decided to not allow two different PHP connection objects rely on single connection while this may lead to hard detectable bugs and unexpected behaviors. If you want to reuse single connection do it explicitly.

**Comment by J-Siu** [comment]
Ok, no problem. Lets close this one. I checked calling pconnect() twice with co1 works.

Thank you!!
