### ISSUE TITLE
Different \AMQPQueue objects in callback function is it possible?

### ISSUE THREAD

**Issue by IvixLabs** [pdezwart/php-amqp#198]
Hello i write one wrapper library for RabbitMq and i found that in one php process possible listen more then one queue.

abstract code for example:

let we have 

exchange1: test.logger(type=fanout)
queue1: test.logger.all(bind to exchange1 with routingKey=null)
queue2: test.logger.specific(bind to exchange1 by error and info routing keys)

then send to exchange1 two messages one with routingKey=info second with routingKey=error

`
$queue1 = new \AMQPQueue($channel);
$queue1->setName('test.logger.specific');
$queue1->consume()

$queue2 = new \AMQPQueue($channel);
$queue2->setName('test.logger.all');
$queue2->consume(function (\AMQPEnvelope $msg, \AMQPQueue $queue) {
            var_dump($msg->getExchangeName(), $queue->getName());
});
`
then output will be
`
string(10) "cms.logger"
string(14) "cms.logger.all"
string(10) "cms.logger"
string(14) "cms.logger.all"
string(10) "cms.logger"
string(14) "cms.logger.all"
string(10) "cms.logger"
string(14) "cms.logger.all"
`

but in rabbitmq panel 2 messages in test.logger.all and 2 in test.logger.specific

Question is second argument will be always same and equals last queue object which invoked consume function with callback function or it is bug and second argument must be different depending of income message?

I hope clear if not ask me i try write more detail.
Thanks

**Comment by pinepain** [comment]
Hi Ivan. Thanks for pointing to this ambiguity (one of many, actually). The second argument to consumer callback is always the queue object which invoked consumer. This is really weird, but is kept for BC reasons. 

For all further readers: **please, don't rely on that second argument in consumer callback. It is always the queue object callback invoked from.**

@lstrojny Maybe we should yield some notice of warning (deprecation warning?) when user pass callback which has more than one parameter? Then in next major release we may drop it, while it is really confusing even to those who familiar with AMQP and RabbitMQ.


P.S. @IvixLabs:

kudos for Mr. Burns picture =). I also wrote a library for dealing with amqp - [pinepain/amqpy](https://github.com/pinepain/amqpy), while it is more a prototype rather than full-fledged production grade solution, there is [driver branch](https://github.com/pinepain/amqpy/tree/driver) where I started some refactoring and was moving towards abstraction on top of php-amqp extension and amqplib library. I you will find it concept useful, let me know and I will try to find some time to finish it.

**Comment by IvixLabs** [comment]
Thanks for answer. 
Then seem need rethink concept and avoid queue name from determination message destination(inside library).

Thank you for show library but my library focused to Symfony2 and made like bundle with some convenient features which will works on Symfony2.

I think possible close issue.
