### ISSUE TITLE
Question about long running consumers

### ISSUE THREAD

**Issue by prolic** [pdezwart/php-amqp#228]
I want to run a consumer on CLI, like forever.

What is the best way to deal with Consumer timeouts? Just consume again in a loop or destroy the consumer and start a new one (supervisord can help here)?

**Comment by lstrojny** [comment]
From using workers in production I find it easier to simply restart the jobs every now and then. We (@InterNations) start our jobs with the timeout binary and we tell supervisor to restart the job.

**Comment by prolic** [comment]
@lstrojny What is a reasonable read timeout then? 600 secs?

**Comment by pinepain** [comment]
It's hard to say exactly which approach is better, more details needed, like what kind of consumers, are there some logic to prepare for consuming that needs cleanup, are there any logic with side effects and so on.

Re-running consumer callback and restarting whole application both may be fine. Though it may be tricky (mostly due to #216, as you noted in #229) to properly re-run consumer. And sometimes restarting whole application might we expensive for various reasons. So it still a controversial topic.

Anyway, restarting is well-known solution which works in most cases fine.

Timeouts mostly mean that there are no data(`read_timeout`) or can't send data to server (`write_timeout`). There are also `connect_timeout` which matters only at connect time. When no data available then it's up to you how to handle such situations. You may wait a bit and switch to other task or wait forever for more data (which is default). But when you can't send data to server it whether you hit some network troubles, firewall or RabbitMQ itself blocks connection. In this case large timeout not always good and it's kinda really exceptional case under which even application restart less likely to help.

**Comment by lstrojny** [comment]
@prolic I don't think there is a general answer for a sane timeout. Depends on how expensive it is for a job to be restarted, how long the job takes to process a single message, how likely the job is to hang and so on. For us we make sure to restart every 1800 seconds but that’s a very specific value that has all kinds of assumptions baked in.

**Comment by prolic** [comment]
Ok, thanks for the feedback.
