### ISSUE TITLE
Access number of jobs currently prefetched on client

### ISSUE THREAD

**Issue by jippi** [pdezwart/php-amqp#244]
Hi

It would be nice if a Channel had a method to expose the number of jobs actually prefetched from the broker.

`Channel::getPrefetchCount()` will return how many jobs it's supposed to fetch, but not how many it actually have fetched.

My usecase is the following:
- my process are running with `queue::consume()` (blocking) and prefetch of 5
- my process gets a signal to die gracefully (async, thanks to `signal_handler` extension)
- my process calls `queue::cancel()` to signal to the broker it should not get more messages
- my process keeps on processing messages it have in the prefetch backlog
- my process consume all of them, but return to a blocking `consume()` waiting for messages

what i would like to know from getting the actual prefetch size on the client, since a prefetch of `100` does not guarantee that the client will have `100` messages.

my current logic basically reads out the `Channel::getPrefetchCount()` and then start counting jobs handled, substracting 1 from the `Channel::getPrefetchCount()` for every job. 

Once this counter reach zero, the process calls `exit(0)` to force a shutdown. 

Now, the problem is the case where `pretch count` is 100, but there are just 3 messages, thus the counter will never reach 0, and thus the process will never exit gracefully.

This is my code: https://gist.github.com/jippi/204aeb9495171e3c0926b40a9e1b09a3

**Relevant lines**

Signal Handler: https://gist.github.com/jippi/204aeb9495171e3c0926b40a9e1b09a3#file-sample-php-L77-L85

Process counter: https://gist.github.com/jippi/204aeb9495171e3c0926b40a9e1b09a3#file-sample-php-L154-L163

Knowing the size of the actual prefetch buffer locally to the client will allow this logic to fully work without the potential risk of getting stuck in `consume()`

**Comment by pinepain** [comment]
Hi

It is also what I want to have, but not sure whether we can access buffer of consumed messages while it is done on a rabbitmq-c (aka librabbitmq) level (a C library to interact with AMQP-compativle brocker, php-amqp extension written on top of it). I'll give it a look but not even sure any similar functionality exists in rabbitmq-c or whether it is public.

P.S.: Second parameter in a callback function to `AMQPQueue::consume()` is deprecated because it is always set to current queue on which `consume()` called (because of legacy codebase and at this time we don't want to break BC).

**Comment by jippi** [comment]
@pinepain alright, thanks for taking your time to investigate it ! really appreciate it!

**Comment by lstrojny** [comment]
Closing this now.
