### ISSUE TITLE
connection_name with RabbitMQ

### ISSUE THREAD

**Issue by Webonaute** [pdezwart/php-amqp#356]
How do I set ClientProperties connection_name with this lib when connecting to rabbitMQ?

**Comment by supersmile2009** [comment]
PR with this feature has been merged recently - https://github.com/pdezwart/php-amqp/pull/363
Connection name can now be set like this:
```
$cnn = new AMQPConnection(['connection_name' => 'Hello world']);
```

@lstrojny I think this issue could be closed now.
BTW any plans on tagging the new version? It's been a while since the last release and a couple of nice features have been merged since then. It would be nice to see v1.10.0 at some point :)

**Comment by lstrojny** [comment]
Closing this.

Tagging a new version: should come in the next couple of days
