### ISSUE TITLE
Non blocking AMQPQueue::consume

### ISSUE THREAD

**Issue by mgtitimoli** [pdezwart/php-amqp#55]
Hi @pdezwart 

First of all, I really thank you that you've shared this great extension with community, I'm working in a project in which we are using it inside a Daemon (php client mode).

After been using it for a while we believe that the following improvement would be nice , as it would allow users to use consume method without blocking the execution. I will detail below how could be the flow using consume in non blocking way.
1. Execute  AMQPQueue::consume ( null, $flags )
2. If consume method was not previously sent, send it, and store that consume has been enabled ( probably in an property called "consumer" that then could be returned calling a new AMQPQueue::isConsumer method)
3. Call read_message_from_channel to retrieve a message (if any) from queue
4. Continue exactly as AMQPQueue::get method is (return a new AMQPEnvelope if message was retrieved or false otherwise)

So to pass it clean two modifications to extension interface need to be done
1. Change consume method to allow it to be called without callback:
   public void AMQPQueue::consume ( callable $callback = null [, int $flags = AMQP_NOPARAM ] )
2. Add a new method
   public bool AMQPQueue::isConsumer ( )
   to retrieve if consume mechanism is enabled on it 

We certainly believe this would be a great improvement to the extension, without involving a lot of development, moreover we can give you a hand with it.

What do you think?

Be well!

**Comment by nejtr0n** [comment]
I've got the same issue. It would be grate to have method like consumeStream(), so we could use it
with https://reactphp.org/.
Now single consume block script executions, so we could not bind multiple consumers in single script.
It has much overhead to make separate process to each queue.
I've tried to fork processes, use pthreads. But library dying with segfault or some other errors.
Are there any way to go consume() in parrallel?

**Comment by pinepain** [comment]
Hi, thanks for asking. As written above, it is less likely to get unblocking consume due to librabbitmq and php-amqp architecture and the nature of PHP itself. While the AMQP nature is asynchronous, the PHP is largely synchronous and here's the challenge - to bring amqp support to php. For ReactPHP you'd probably have to write your own adapter, I guess php-amqplib could be altered to work with react, if not yet. 

Also note, that *all* php-amqp resources (connection, channel, queue) are single-threaded and you can not share anything withing single connection between threads safely, at least this is not taken into account while designing php-amqp, afak.

**Comment by nejtr0n** [comment]
I thought something changed from time issue was open. (But may be not documented yet)
Fortunately php-amqplib have non-blocking consume. Thank you for help!
